// Give the debug build its own application id, so a dev client and the
// released app can sit on one phone at the same time.
//
// WHY THIS EXISTS. Android identifies an app by package name PLUS signing key.
// After the package was renamed to dev.bismark.twitwa for the 1.0.1 release,
// the debug build and the release build wanted the same id and carried
// different keys -- the debug keystore and the project's own. Installing one
// over the other fails with INSTALL_FAILED_UPDATE_INCOMPATIBLE, so verifying a
// UI change on the device meant uninstalling the released app first. That is
// the wrong trade every single time: the released install is the only copy of
// the state the update path was tested against.
//
// With this, the debug variant installs as dev.bismark.twitwa.debug and the
// two coexist. `adb shell pm list packages | grep twitwa` shows both, and
// every device script has to name which one it means -- which it should
// anyway, because they run different programs.
//
// WHY A CONFIG PLUGIN AND NOT AN EDIT TO android/app/build.gradle. Same reason
// as plugins/withReleaseSigning.js: android/ is generated by `expo prebuild`
// and is gitignored, so a direct edit is erased by the next prebuild and was
// never in the repository at all.
//
// WHAT IT DOES NOT DO. It does not rename the launcher entry, so both builds
// appear as "Twitwa" in the drawer. A resValue for app_name collides with the
// template's own strings.xml entry, and the icons are the thing people
// actually pick by. `adb shell monkey -p <id>` is unambiguous either way.

// The template's debug buildType, matched whole. If Expo changes it, patch()
// throws at prebuild rather than quietly leaving the two builds sharing an id
// -- which looks like a working build right up to the install.
const DEBUG_BLOCK = `        debug {
            signingConfig signingConfigs.debug
        }`;

const DEBUG_BLOCK_PATCHED = `        debug {
            // plugins/withDebugSuffix.js: coexist with the released app, which
            // carries the same package name and a different signing key.
            applicationIdSuffix '.debug'
            signingConfig signingConfigs.debug
        }`;

const SUFFIX = '.debug';

/**
 * Add applicationIdSuffix to the debug buildType, and read back that exactly
 * one was added and that the release buildType did not get one.
 *
 * A suffix on release would be the expensive version of this mistake: an APK
 * published under an id nobody can upgrade from.
 */
function patch(contents) {
  if (contents.includes('applicationIdSuffix')) return contents; // already applied

  if (!contents.includes(DEBUG_BLOCK)) {
    throw new Error(
      'withDebugSuffix: could not find the debug buildType in ' +
        'android/app/build.gradle. The Expo template changed. Re-read the file ' +
        'and update the anchor in plugins/withDebugSuffix.js.',
    );
  }

  const out = contents.replace(DEBUG_BLOCK, DEBUG_BLOCK_PATCHED);

  const count = out.split('applicationIdSuffix').length - 1;
  if (count !== 1) {
    throw new Error(
      `withDebugSuffix: wrote ${count} applicationIdSuffix lines, expected 1.`,
    );
  }
  // The release buildType, which is NOT simply the first `release {` in the
  // file. withReleaseSigning adds a `release {` to signingConfigs at the same
  // indent, and it comes first; slicing from that swept up the buildTypes
  // debug block and made this guard refuse a correct patch. Found by the
  // signing suite's byte-for-byte check, which applies both plugins in the
  // order app.json declares them.
  const types = out.indexOf('    buildTypes {');
  const release = types === -1 ? '' : out.slice(out.indexOf('        release {', types));
  if (release.includes('applicationIdSuffix')) {
    throw new Error(
      'withDebugSuffix: the suffix landed in the release buildType. A released ' +
        'APK under a suffixed id cannot be upgraded from the published one.',
    );
  }
  return out;
}

module.exports = function withDebugSuffix(config) {
  const { withAppBuildGradle } = require('@expo/config-plugins');
  return withAppBuildGradle(config, (cfg) => {
    if (cfg.modResults.language !== 'groovy') {
      throw new Error(
        'withDebugSuffix: expected a Groovy build.gradle, got ' + cfg.modResults.language,
      );
    }
    cfg.modResults.contents = patch(cfg.modResults.contents);
    return cfg;
  });
};

// Exported for the test: the plugin itself is only exercisable by a prebuild,
// and the string surgery is the part that can half-apply.
module.exports.patch = patch;
module.exports.strings = { DEBUG_BLOCK, DEBUG_BLOCK_PATCHED, SUFFIX };
