// Sign the release build with the project's own key instead of the debug key.
//
// Why this is a config plugin and not an edit to android/app/build.gradle:
// android/ is generated by `expo prebuild` and is gitignored, so a direct edit
// is erased by the next prebuild and was never in the repository to begin with.
// A plugin is the only form of this fix that survives.
//
// What it fixes. The Expo/RN template ships `release { signingConfig
// signingConfigs.debug }` with a comment warning you about it, so a release APK
// is signed by the debug key that every RN project on earth shares. That is not
// a theoretical problem for an app handed to friends: Android identifies an app
// by package name plus signing key, so anyone could build an APK that installs
// over it as an update, and the day the real key is introduced every recipient
// has to uninstall first, losing their Library.
//
// Where the key lives. Outside the repository, and named by the environment
// variable TWITWA_KEYSTORE_PROPERTIES pointing at a keystore.properties file.
// No path and no secret is committed, which is what lets this repository be
// public. If the variable is unset or the file is missing, the build falls back
// to debug signing and says so in the Gradle log — a clone by someone else
// still builds, it just does not produce a distributable APK.
// `@expo/config-plugins` is required lazily, inside the exported plugin, and
// not at module scope. Two reasons, both found by review:
//  - the test mutates THIS FILE's source and loads the mutant from a temp
//    directory, which cannot resolve the project's node_modules. A top-level
//    require made every mutant fail to load, which is indistinguishable from a
//    mutant the assertions caught.
//  - it lets tools/check-imports.mjs actually load this module rather than
//    parse it, so a wrong named import here is caught like any other.
const fs = require('fs');
const path = require('path');

// Prepended to android/app/build.gradle when the patch cannot be applied, so
// that the tree prebuild leaves behind cannot be built.
//
// This is here because of a review finding that falsified the comment above it.
// `expo prebuild` writes the native template to disk FIRST (prebuildAsync.js
// calls updateFromTemplateAsync before compileModsAsync), and only then runs
// mods. So when this plugin throws, prebuild does exit non-zero -- but it has
// already left a complete, buildable, PRISTINE android/ tree whose release
// buildType still reads `signingConfig signingConfigs.debug`. Running
// `cd android && ./gradlew assembleRelease` at that point produces a
// debug-signed APK with no warning whatsoever, because the loader that would
// have printed one never made it into the file.
//
// Throwing is therefore loud at prebuild and silent at the step that matters.
// A Gradle-level throw at the top of the file closes that: every task fails,
// with the reason, until someone fixes the anchors and re-runs prebuild.
const POISON_HEADER = `// ---------------------------------------------------------------------------
// TWITWA: THIS FILE IS DELIBERATELY UNBUILDABLE.
//
// plugins/withReleaseSigning.js could not find its anchors in the template
// Expo generated, so release signing was NOT applied. prebuild had already
// written this file before the plugin ran, so without the line below you could
// build a DEBUG-SIGNED release APK from it and nothing would say so.
//
// Fix: re-read android/app/build.gradle against the anchors in
// plugins/withReleaseSigning.js, update them, then re-run
// \`npx expo prebuild -p android --clean\`.
// ---------------------------------------------------------------------------
throw new GradleException("Twitwa: release signing was not applied to this build.gradle (see the comment at the top of this file). Refusing to build rather than produce a debug-signed release.")

`;

// Anchor A: the template's signingConfigs block, matched whole. If Expo changes
// it, the assert below fails loudly at prebuild rather than silently producing a
// debug-signed release, which is the failure that must never be quiet.
const SIGNING_CONFIGS = `    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }`;

const SIGNING_CONFIGS_PATCHED = `    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
        release {
            if (twitwaKeystore != null) {
                storeFile file(twitwaKeystore.getProperty('storeFile'))
                storePassword twitwaKeystore.getProperty('storePassword')
                keyAlias twitwaKeystore.getProperty('keyAlias')
                keyPassword twitwaKeystore.getProperty('keyPassword')
            }
        }
    }`;

// Anchor B: the template's own warning plus the line it warns about.
const RELEASE_SIGNING = `            // Caution! In production, you need to generate your own keystore file.
            // see https://reactnative.dev/docs/signed-apk-android.
            signingConfig signingConfigs.debug`;

const RELEASE_SIGNING_PATCHED = `            // Signed by the project's own key when TWITWA_KEYSTORE_PROPERTIES is
            // set; see plugins/withReleaseSigning.js. Falls back to the debug key
            // so a clone still builds, and the log above says which one was used.
            signingConfig twitwaKeystore != null ? signingConfigs.release : signingConfigs.debug`;

// Loaded before the android {} block, so signingConfigs can read it.
const LOADER = `
// --- Twitwa release signing (plugins/withReleaseSigning.js) ----------------
// Read once, at configuration time. The properties file is outside the repo and
// named by an environment variable, so no key material or local path is
// committed.
def twitwaKeystore = null
def twitwaKeystorePath = System.getenv('TWITWA_KEYSTORE_PROPERTIES')
if (twitwaKeystorePath != null && !twitwaKeystorePath.isEmpty() && file(twitwaKeystorePath).exists()) {
    twitwaKeystore = new Properties()
    file(twitwaKeystorePath).withInputStream { twitwaKeystore.load(it) }
    logger.lifecycle("Twitwa: release builds will be signed with the key named by TWITWA_KEYSTORE_PROPERTIES")
} else if (twitwaKeystorePath != null && !twitwaKeystorePath.isEmpty()) {
    throw new GradleException("TWITWA_KEYSTORE_PROPERTIES is set to '" + twitwaKeystorePath + "' but that file does not exist. Refusing to fall back to debug signing silently.")
} else {
    logger.lifecycle("Twitwa: TWITWA_KEYSTORE_PROPERTIES is unset, so a release build will be DEBUG-SIGNED and is not distributable")
}

android {`;

function patch(contents) {
  if (contents.includes('twitwaKeystore')) return contents; // already applied

  const misses = [];
  if (!contents.includes(SIGNING_CONFIGS)) misses.push('signingConfigs block');
  if (!contents.includes(RELEASE_SIGNING)) misses.push('release signingConfig line');
  if (!contents.includes('\nandroid {')) misses.push('android { block');
  if (misses.length) {
    // Loud, not quiet. A missed anchor here means a release APK signed by the
    // shared debug key, which is exactly the outcome this plugin exists to stop.
    throw new Error(
      'withReleaseSigning: could not find ' + misses.join(', ') +
        ' in android/app/build.gradle. The Expo template changed. Re-read the file and update the anchors; do NOT ship a release build until this passes.',
    );
  }

  return contents
    .replace('\nandroid {', LOADER)
    .replace(SIGNING_CONFIGS, SIGNING_CONFIGS_PATCHED)
    .replace(RELEASE_SIGNING, RELEASE_SIGNING_PATCHED);
}

/**
 * Make the tree prebuild already wrote unbuildable, then let the error through.
 *
 * Writing to disk from inside a mod is a side effect and normally the wrong
 * shape. It is right here for one reason: a throw does NOT undo the template
 * prebuild has already written, and the leftover is a debug-signed release
 * waiting to be built. Failing closed beats failing loudly.
 */
function poisonOnDisk(cfg) {
  try {
    const p = path.join(cfg.modRequest.platformProjectRoot, 'app', 'build.gradle');
    if (!fs.existsSync(p)) return false;
    const current = fs.readFileSync(p, 'utf8');
    if (current.startsWith('// ------') && current.includes('THIS FILE IS DELIBERATELY UNBUILDABLE')) {
      return true; // already poisoned; do not stack headers
    }
    fs.writeFileSync(p, POISON_HEADER + current);
    return true;
  } catch (e) {
    // Never let the poisoning failure mask the original one.
    return false;
  }
}

module.exports = function withReleaseSigning(config) {
  const { withAppBuildGradle } = require('@expo/config-plugins');
  return withAppBuildGradle(config, (cfg) => {
    if (cfg.modResults.language !== 'groovy') {
      poisonOnDisk(cfg);
      throw new Error(
        'withReleaseSigning: expected a Groovy build.gradle, got ' + cfg.modResults.language,
      );
    }
    try {
      cfg.modResults.contents = patch(cfg.modResults.contents);
    } catch (e) {
      const poisoned = poisonOnDisk(cfg);
      e.message +=
        '\n\nandroid/app/build.gradle ' +
        (poisoned
          ? 'has been made unbuildable on purpose, because prebuild had already written a debug-signed template before this plugin ran. Fix the anchors and re-run prebuild.'
          : 'could NOT be made unbuildable, so a debug-signed release APK can still be built from it. Delete android/ before building anything.');
      throw e;
    }
    return cfg;
  });
};

// Exported for the test. The plugin itself is only exercisable by a prebuild;
// the string surgery is not, and that is the part that can silently half-apply.
//
// Both halves of each substitution are exported, not just the anchors, so the
// test can invert the patch to recover the pristine template from a generated
// file that has already been patched. That is how the fixture beside this file
// was produced: it is not a hand-copied snapshot.
module.exports.patch = patch;
module.exports.poisonOnDisk = poisonOnDisk;
module.exports.POISON_HEADER = POISON_HEADER;
// One object, not two. `anchors` used to be a second, narrower export beside
// `strings`, and the test imported `anchors` while re-typing eight substrings
// that already lived inside `strings` — so `strings` was a dead export that
// check-dead.mjs could not see (it matches ESM `export`, and this module is
// CommonJS), and the retyped copies were free to drift. A review found both.
module.exports.strings = {
  SIGNING_CONFIGS,
  SIGNING_CONFIGS_PATCHED,
  RELEASE_SIGNING,
  RELEASE_SIGNING_PATCHED,
  LOADER,
  VAR: 'twitwaKeystore',
  ENV: 'TWITWA_KEYSTORE_PROPERTIES',
  GRADLE_THROW: 'throw new GradleException(',
  REFUSE_MESSAGE: 'Refusing to fall back to debug signing silently',
  DEBUG_STORE: "storeFile file('debug.keystore')",
};
