// Tell the share-in module when MainActivity is being RESTORED, before the
// saved state is thrown away.
//
// WHY THIS EXISTS. A share is read once, and the "read" mark lives on the
// Intent object in this process. When Android kills Twitwa in the background
// and later rebuilds the activity, it hands over its own copy of the intent,
// unmarked, and the old picture would be imported again. The one thing that
// tells a restore apart from a new launch is a non-null `savedInstanceState`.
//
// Expo's template MainActivity passes NULL to `super.onCreate`, so nothing
// downstream -- no ReactActivityLifecycleListener, no Application callback
// dispatched from Activity.onCreate -- ever sees the real Bundle. The first
// fix listened there and could not work; the Pixel showed the replay on
// 2026-09-23. See modules/twitwa-share-in/.../ShareInRestore.kt.
//
// So this writes one call into MainActivity.onCreate, above the line that
// drops the state. The call names a function in the share-in module rather
// than writing the mark's extra here, so the mark's name has one home.
//
// WHY A CONFIG PLUGIN. Same reason as plugins/withDebugSuffix.js: android/ is
// generated by `expo prebuild` and is gitignored, so a direct edit is erased by
// the next prebuild and was never in the repository at all.

// The template's line, matched whole with its indent. If Expo changes it,
// patch() throws at prebuild rather than quietly shipping the replay again.
const ANCHOR = '    super.onCreate(null)\n';

const CALL = 'dev.bismark.twitwa.sharein.ShareInRestore.markIfRestored(this, savedInstanceState)';

const INSERT =
  '    // plugins/withShareInRestore.js: a restored share is not a new one, and\n' +
  '    // the next line drops the state that says so.\n' +
  `    ${CALL}\n`;

/**
 * Insert the call above `super.onCreate(null)`, having checked that the anchor
 * sits inside onCreate. Exactly one call, before the anchor, is fixed by
 * construction -- one splice at the anchor's own index, after the early return
 * for a file already patched -- and the test asserts both on the output.
 */
function patch(contents) {
  const text = contents.replace(/\r\n/g, '\n');
  if (text.includes(CALL)) return contents; // already applied

  const at = text.indexOf(ANCHOR);
  if (at === -1 || text.indexOf(ANCHOR, at + 1) !== -1) {
    throw new Error(
      'withShareInRestore: expected exactly one `super.onCreate(null)` in ' +
        'MainActivity.kt. The Expo template changed. Re-read the file and ' +
        'update the anchor in plugins/withShareInRestore.js.',
    );
  }
  const onCreate = text.lastIndexOf('override fun onCreate(savedInstanceState: Bundle?)', at);
  if (onCreate === -1 || text.slice(onCreate, at).includes('\n  }')) {
    throw new Error(
      'withShareInRestore: `super.onCreate(null)` is not inside ' +
        '`onCreate(savedInstanceState: Bundle?)` in MainActivity.kt, so ' +
        '`savedInstanceState` would not be the Bundle the call needs.',
    );
  }

  return text.slice(0, at) + INSERT + text.slice(at);
}

module.exports = function withShareInRestore(config) {
  const { withMainActivity } = require('@expo/config-plugins');
  return withMainActivity(config, (cfg) => {
    if (cfg.modResults.language !== 'kt') {
      throw new Error(
        'withShareInRestore: expected a Kotlin MainActivity, got ' + cfg.modResults.language,
      );
    }
    cfg.modResults.contents = patch(cfg.modResults.contents);
    return cfg;
  });
};

// Exported for the test: the plugin itself is only exercisable by a prebuild,
// and the string surgery is the part that can half-apply.
module.exports.patch = patch;
module.exports.strings = { ANCHOR, CALL, INSERT };
// The file patch() is for. The signing suite composes every plugin's patch
// over build.gradle, and this is how it knows to leave this one out.
module.exports.target = 'MainActivity.kt';
